import { mkdir, writeFile, cp, readFile } from 'node:fs/promises';
import { createDemoBoard, serializeBoard } from '../src/model';
const { version } = JSON.parse(await readFile('manifest.json', 'utf8'));
const root = `test-vault-${version}`;
const board = createDemoBoard();
await mkdir(`${root}/.obsidian/plugins`, { recursive: true });
await mkdir(`${root}/LinB Kanban/附件/${board.id}`, { recursive: true });
await cp('dist/linb-kanban', `${root}/.obsidian/plugins/linb-kanban`, { recursive: true });
const file = `LinB Kanban/${board.title}.md`;
await writeFile(`${root}/${file}`, serializeBoard(board, 'LinB Kanban'));
await writeFile(`${root}/.obsidian/community-plugins.json`, JSON.stringify(['linb-kanban']));
await writeFile(`${root}/.obsidian/app.json`, JSON.stringify({ showUnsupportedFiles: true }));
await writeFile(`${root}/.obsidian/appearance.json`, JSON.stringify({ theme: 'moonstone', baseFontSize: 16 }));
await writeFile(`${root}/.obsidian/workspace.json`, JSON.stringify({ main: { id: 'linb-test-root', type: 'split', children: [{ id: 'linb-test-tabs', type: 'tabs', children: [{ id: 'linb-test-leaf', type: 'leaf', state: { type: 'linb-kanban-view', state: { file }, icon: 'copy-plus', title: board.title } }] }], direction: 'vertical' }, active: 'linb-test-leaf' }));
await writeFile(`${root}/README.md`, '# LinB Kanban 独立测试库\n\n此文件夹仅用于验证新插件，不包含个人笔记。\n');
console.log(`Prepared ${root}/${file}`);
